[pytest]
testpaths = tests policy/training evaluation i2i/training/roi_random500
pythonpath = policy/training evaluation evaluation/i2i_service i2i/training/roi_random500 policy/source
addopts = -p no:cacheprovider
