#!/usr/bin/env python3
"""Build the strict RoboTwin official50 x clean50 manual-goal runtime dataset.

The runtime root is deliberately lightweight: official LeRobot v3 parquet and
videos remain in the immutable source root and are exposed through symlinks.
Only compatibility metadata, the authoritative family map, manually designed
goal annotations, the goal-graph specification, and the training manifest are
created locally.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable

import h5py
import numpy as np
import pyarrow.parquet as pq


SCHEMA_VERSION = "robotwin-official50-clean50-manualgoal/v2"
SPLIT_SCHEMA_VERSION = "robotwin-semantic-split/v1"
ANNOTATION_SCHEMA_VERSION = "robotwin-manual-subgoal-annotation/v2"
GOAL_GRAPH_VERSION = "official50-clean50-stage-success-v6-22s28e/v2"

POLICY_ROOT_CANDIDATES = (Path(__file__).resolve().parents[1] / "policy",)
for _policy_root in POLICY_ROOT_CANDIDATES:
    if (_policy_root / "cosmos_policy/stage_success.py").is_file():
        sys.path.insert(0, str(_policy_root))
        break
else:
    raise FileNotFoundError(
        "cannot locate cosmos_policy/stage_success.py; checked "
        f"{[str(path) for path in POLICY_ROOT_CANDIDATES]}"
    )

from cosmos_policy.stage_success import (  # noqa: E402
    STAGE_CONTRACT_VERSION,
    SUBGOAL_TASKS,
    TASK_STAGE_CRITERIA,
    TASK_STAGE_TEXTS,
)

DEFAULT_BASE = Path(os.environ.get("VIGAR_SOURCE_DATASET", "/path/to/source_lerobot_dataset"))
DEFAULT_RAW = Path(os.environ.get("VIGAR_RAW_TRAJECTORIES", "/path/to/raw_by_task"))
DEFAULT_OUTPUT = Path(os.environ.get("VIGAR_DATASET_V6", "/path/to/stage_v6"))
DEFAULT_STAGE_BOUNDARIES = Path(os.environ.get("VIGAR_STAGE_BOUNDARIES", "/path/to/stage_boundaries_v6.jsonl"))

MANUAL_STAGE_TEXT = {
    task_name: list(texts) for task_name, texts in TASK_STAGE_TEXTS.items()
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base-root", type=Path, default=DEFAULT_BASE)
    parser.add_argument("--raw-root", type=Path, default=DEFAULT_RAW)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--stage-boundaries",
        type=Path,
        default=DEFAULT_STAGE_BOUNDARIES,
        help=(
            "complete 22x50 expert-replay boundary JSONL generated by "
            "extract_stage_boundaries.py"
        ),
    )
    parser.add_argument(
        "--audit-only",
        action="store_true",
        help="validate all inputs and print the prospective boundary audit without writing",
    )
    return parser.parse_args()


def canonical_json_bytes(value: Any) -> bytes:
    return json.dumps(
        value, ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        while chunk := stream.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def write_json(path: Path, value: Any) -> None:
    path.write_text(
        json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n",
        encoding="utf-8",
    )


def write_jsonl(path: Path, rows: Iterable[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8") as stream:
        for row in rows:
            stream.write(canonical_json_bytes(row).decode("utf-8"))
            stream.write("\n")


def find_episode_metadata(base_root: Path) -> list[dict[str, Any]]:
    files = sorted((base_root / "meta/episodes").glob("**/*.parquet"))
    if not files:
        raise FileNotFoundError(f"no episode parquet under {base_root}/meta/episodes")
    rows: list[dict[str, Any]] = []
    for path in files:
        table = pq.read_table(path, columns=["episode_index", "tasks", "length"])
        rows.extend(table.to_pylist())
    rows.sort(key=lambda row: int(row["episode_index"]))
    indices = [int(row["episode_index"]) for row in rows]
    if indices != list(range(2500)):
        raise ValueError(
            f"official source must contain exactly episode indices 0..2499; got {len(indices)} rows"
        )
    return rows


def task_directories(raw_root: Path) -> list[Path]:
    result = sorted(path for path in raw_root.iterdir() if path.is_dir())
    if len(result) != 50:
        raise ValueError(f"raw root must contain exactly 50 task directories; got {len(result)}")
    return result


def event_frames(values: np.ndarray) -> tuple[list[int], list[int]]:
    """Return threshold-crossing (close, open) frame indices."""

    vector = np.asarray(values).reshape(-1)
    is_open = vector >= 0.5
    close = [
        index
        for index in range(1, len(vector))
        if bool(is_open[index - 1]) and not bool(is_open[index])
    ]
    opened = [
        index
        for index in range(1, len(vector))
        if not bool(is_open[index - 1]) and bool(is_open[index])
    ]
    return close, opened


def stage_texts(family: str, count: int, episode_prompt: str) -> list[str]:
    if family not in SUBGOAL_TASKS:
        if count != 1:
            raise AssertionError((family, count))
        return [episode_prompt]
    choices = MANUAL_STAGE_TEXT[family]
    if family == "place_bread_basket" and count == 1:
        return [choices[-1]]
    if len(choices) != count:
        raise ValueError(
            f"stage-text mismatch for {family}: texts={len(choices)}, endpoints={count}"
        )
    return choices


def source_task_data_dir(task_dir: Path) -> Path:
    candidates = sorted(task_dir.glob("demo_clean*/data"))
    if len(candidates) != 1:
        raise ValueError(f"expected one demo_clean*/data under {task_dir}; got {candidates}")
    return candidates[0]


def load_grippers(path: Path) -> tuple[int, np.ndarray, np.ndarray]:
    with h5py.File(path, "r") as handle:
        left = np.asarray(handle["joint_action/left_gripper"][:])
        right = np.asarray(handle["joint_action/right_gripper"][:])
        vector_length = int(handle["joint_action/vector"].shape[0])
    if len(left) != vector_length or len(right) != vector_length:
        raise ValueError(f"inconsistent action lengths in {path}")
    return vector_length, left, right


def load_stage_boundaries(path: Path) -> dict[tuple[str, int], dict[str, Any]]:
    if not path.is_file():
        raise FileNotFoundError(
            f"v6 stage boundary manifest is required and was not found: {path}"
        )
    records: dict[tuple[str, int], dict[str, Any]] = {}
    with path.open(encoding="utf-8") as stream:
        for line_number, line in enumerate(stream, 1):
            if not line.strip():
                continue
            row = json.loads(line)
            if row.get("contract_version") != STAGE_CONTRACT_VERSION:
                raise ValueError(
                    f"stage boundary line {line_number} has contract "
                    f"{row.get('contract_version')!r}, expected {STAGE_CONTRACT_VERSION!r}"
                )
            key = (str(row["task"]), int(row["local_episode_index"]))
            if key in records:
                raise ValueError(f"duplicate v6 stage boundary record {key}")
            records[key] = row
    expected = {
        (task_name, local_index)
        for task_name in SUBGOAL_TASKS
        for local_index in range(50)
    }
    missing = sorted(expected - set(records))
    extra = sorted(set(records) - expected)
    if missing or extra:
        raise ValueError(
            "v6 stage boundary coverage must be exactly 22x50; "
            f"records={len(records)} missing={missing[:10]} extra={extra[:10]}"
        )
    return records


def build_records(
    base_root: Path, raw_root: Path, stage_boundaries_path: Path
) -> tuple[
    dict[str, dict[str, Any]],
    list[dict[str, Any]],
    dict[str, Any],
    dict[str, Any],
]:
    episodes = find_episode_metadata(base_root)
    task_dirs = task_directories(raw_root)
    family_names = [path.name for path in task_dirs]
    if len(SUBGOAL_TASKS) != 22:
        raise AssertionError(f"expected 22 subgoal families, got {len(SUBGOAL_TASKS)}")
    unknown = sorted(SUBGOAL_TASKS - set(family_names))
    if unknown:
        raise ValueError(f"subgoal tasks missing from official source: {unknown}")
    stage_boundary_records = load_stage_boundaries(stage_boundaries_path)

    annotations: dict[str, dict[str, Any]] = {}
    mapping_rows: list[dict[str, Any]] = []
    audit_rows: list[dict[str, Any]] = []
    counts_by_family: dict[str, Counter[int]] = defaultdict(Counter)
    strategy_counts: dict[str, Counter[str]] = defaultdict(Counter)

    for family_index, task_dir in enumerate(task_dirs):
        data_dir = source_task_data_dir(task_dir)
        source_root = data_dir.parent
        source_seeds = [
            int(value) for value in (source_root / "seed.txt").read_text().split()
        ]
        if len(source_seeds) != 50:
            raise ValueError(
                f"{task_dir.name} must expose exactly 50 ordered seeds"
            )
        hdf5_paths = {int(path.stem.removeprefix("episode")): path for path in data_dir.glob("episode*.hdf5")}
        if sorted(hdf5_paths) != list(range(50)):
            raise ValueError(
                f"{task_dir.name} must contain local episodes 0..49; got {len(hdf5_paths)}"
            )
        for local_index in range(50):
            global_index = family_index * 50 + local_index
            row = episodes[global_index]
            if int(row["episode_index"]) != global_index:
                raise AssertionError(global_index)
            tasks = row.get("tasks") or []
            if not isinstance(tasks, list) or not tasks or not str(tasks[0]).strip():
                raise ValueError(f"episode {global_index} has no task prompt")
            prompt = str(tasks[0]).strip()
            length = int(row["length"])
            raw_length, left, right = load_grippers(hdf5_paths[local_index])
            if raw_length != length:
                raise ValueError(
                    f"length mismatch episode {global_index} {task_dir.name}/{local_index}: "
                    f"raw={raw_length}, v3={length}"
                )

            left_close, left_open = event_frames(left)
            right_close, right_open = event_frames(right)
            boundary_record = None
            if task_dir.name in SUBGOAL_TASKS:
                boundary_record = stage_boundary_records[
                    (task_dir.name, local_index)
                ]
                if int(boundary_record["seed"]) != source_seeds[local_index]:
                    raise ValueError(
                        f"seed mismatch for {task_dir.name}/{local_index}: "
                        f"boundary={boundary_record['seed']} "
                        f"source={source_seeds[local_index]}"
                    )
                if int(boundary_record["frame_count"]) != length:
                    raise ValueError(
                        f"boundary length mismatch for {task_dir.name}/{local_index}: "
                        f"boundary={boundary_record['frame_count']} source={length}"
                    )
                endpoints = [
                    int(stage["end_frame"])
                    for stage in boundary_record["stages"]
                ]
                strategy = "v6_first_stage_success"
            else:
                endpoints, strategy = [length], "episode_goal"
            texts = stage_texts(task_dir.name, len(endpoints), prompt)
            if boundary_record is not None:
                replay_texts = [
                    str(stage["subtask_text"])
                    for stage in boundary_record["stages"]
                ]
                if texts != replay_texts:
                    raise ValueError(
                        f"stage text mismatch for {task_dir.name}/{local_index}"
                    )
            steps: list[dict[str, Any]] = []
            start = 0
            for stage_index, (end, text) in enumerate(zip(endpoints, texts)):
                if not (start < end <= length):
                    raise ValueError(
                        f"invalid endpoint episode {global_index}: start={start}, end={end}, length={length}"
                    )
                semantic_stage_index = stage_index
                if (
                    task_dir.name == "place_bread_basket"
                    and len(endpoints) == 1
                ):
                    # A one-bread episode contains only the canonical terminal
                    # node.  Keep its contiguous annotation index at zero, but
                    # assign its sampling unit to terminal stage 1 instead of
                    # contaminating the first-bread stage-0 budget.
                    semantic_stage_index = len(
                        TASK_STAGE_TEXTS[task_dir.name]
                    ) - 1
                steps.append(
                    {
                        "track": "default",
                        "start_frame": start,
                        "end_frame": end,
                        "action_text": text,
                        "skill": text,
                        "is_mistake": False,
                        "info": {
                            "family": task_dir.name,
                            "stage_index": stage_index,
                            "semantic_stage_index": semantic_stage_index,
                            "stage_count": len(endpoints),
                            "boundary_source": strategy,
                            "stage_contract_version": (
                                STAGE_CONTRACT_VERSION
                                if task_dir.name in SUBGOAL_TASKS
                                else None
                            ),
                            "stage_criterion": (
                                TASK_STAGE_CRITERIA[task_dir.name][
                                    semantic_stage_index
                                ].name
                                if task_dir.name in SUBGOAL_TASKS
                                else None
                            ),
                        },
                    }
                )
                start = end

            annotations[str(global_index)] = {
                "schema_version": ANNOTATION_SCHEMA_VERSION,
                "episode_id": global_index,
                "episode_index": global_index,
                "frame_count": length,
                "task_name": prompt,
                "family": task_dir.name,
                "goal_mode": "subgoal" if task_dir.name in SUBGOAL_TASKS else "episode_goal",
                "goal_graph_version": GOAL_GRAPH_VERSION,
                "source_local_episode_index": local_index,
                "source_hdf5": str(hdf5_paths[local_index]),
                "action_steps": steps,
                "key_frame": {
                    "single": [end - 1 for end in endpoints],
                    "dual": [],
                },
            }
            mapping_rows.append(
                {
                    "episode_index": global_index,
                    "family": task_dir.name,
                    "family_index": family_index,
                    "local_episode_index": local_index,
                    "task": prompt,
                    "length": length,
                    "source_hdf5": str(hdf5_paths[local_index]),
                }
            )
            counts_by_family[task_dir.name][len(endpoints)] += 1
            strategy_counts[task_dir.name][strategy] += 1
            audit_rows.append(
                {
                    "episode_index": global_index,
                    "family": task_dir.name,
                    "local_episode_index": local_index,
                    "length": length,
                    "goal_mode": "subgoal" if task_dir.name in SUBGOAL_TASKS else "episode_goal",
                    "endpoints": endpoints,
                    "normalized_endpoints": [round(end / length, 6) for end in endpoints],
                    "left_close": left_close,
                    "left_open": left_open,
                    "right_close": right_close,
                    "right_open": right_open,
                    "strategy": strategy,
                }
            )

    if set(map(int, annotations)) != set(range(2500)):
        raise AssertionError("annotation coverage is not exactly 0..2499")

    family_map = {
        "schema_version": "robotwin-explicit-family-map/v1",
        "source_dataset": str(base_root),
        "task_order": family_names,
        "episodes_per_family": 50,
        "total_episodes": 2500,
        "episodes": mapping_rows,
    }
    goal_graph = {
        "schema_version": "robotwin-manual-goal-graph/v2",
        "version": GOAL_GRAPH_VERSION,
        "design": {
            "total_families": 50,
            "subgoal_families": 22,
            "episode_goal_families": 28,
            "principle": (
                "Each fixed goal frame is the first recorded expert frame where the same "
                "stage-success predicate used by online switching and atomic evaluation "
                "becomes true; retain official task success for every terminal stage."
            ),
            "stage_contract_version": STAGE_CONTRACT_VERSION,
            "switch_confirmation_steps": 1,
            "switch_latch": "monotonic",
            "annotation_application": "already_materialized; do not apply a second runtime goal graph",
        },
        "families": {
            family: {
                "mode": "subgoal" if family in SUBGOAL_TASKS else "episode_goal",
                "stage_texts": MANUAL_STAGE_TEXT.get(family, ["episode task prompt"]),
                "stage_criteria": (
                    [
                        {"name": row.name, "description": row.description}
                        for row in TASK_STAGE_CRITERIA[family]
                    ]
                    if family in SUBGOAL_TASKS
                    else []
                ),
                "boundary_resolver": (
                    "first recorded frame where authoritative v6 stage_success is true"
                    if family in SUBGOAL_TASKS
                    else "terminal frame"
                ),
                "observed_subtask_counts": sorted(counts_by_family[family]),
                "count_histogram": {
                    str(key): value for key, value in sorted(counts_by_family[family].items())
                },
                "boundary_strategy_histogram": dict(sorted(strategy_counts[family].items())),
            }
            for family in family_names
        },
    }
    audit = {
        "schema_version": "robotwin-manual-goal-boundary-audit/v2",
        "goal_graph_version": GOAL_GRAPH_VERSION,
        "stage_contract_version": STAGE_CONTRACT_VERSION,
        "summary": {
            "episodes": 2500,
            "families": 50,
            "subgoal_families": 22,
            "episode_goal_families": 28,
            "subtasks": sum(len(value["action_steps"]) for value in annotations.values()),
            "fallback_episodes": 0,
            "terminal_replay_exceptions": sum(
                not bool(row.get("terminal_replay_official_success", True))
                for row in stage_boundary_records.values()
            ),
        },
        "episodes": audit_rows,
    }
    return annotations, mapping_rows, family_map, {
        "goal_graph": goal_graph,
        "audit": audit,
        "stage_boundary_rows": [
            stage_boundary_records[key] for key in sorted(stage_boundary_records)
        ],
        "stage_boundaries_sha256": sha256_file(stage_boundaries_path),
    }


def source_hashes(meta_root: Path) -> dict[str, str]:
    paths = {
        "info.json": meta_root / "info.json",
        "episodes.jsonl": meta_root / "episodes.jsonl",
        "tasks.jsonl": meta_root / "tasks.jsonl",
        "annotations.json": meta_root / "annotations.json",
    }
    return {name: sha256_file(path) for name, path in paths.items()}


def metadata_digest(hashes: dict[str, str]) -> str:
    names = ("info.json", "episodes.jsonl", "tasks.jsonl", "annotations.json")
    payload = [{"name": name, "sha256": hashes[name]} for name in names]
    return sha256_bytes(canonical_json_bytes(payload))


def build_manifest(
    annotations: dict[str, dict[str, Any]],
    mapping_rows: list[dict[str, Any]],
    hashes: dict[str, str],
) -> dict[str, Any]:
    rows = [
        {
            "episode_index": int(row["episode_index"]),
            "family": str(row["family"]),
            "split": "train",
        }
        for row in mapping_rows
    ]
    assignment_hash = sha256_bytes(canonical_json_bytes(rows))
    by_family: dict[str, list[int]] = defaultdict(list)
    for row in rows:
        by_family[row["family"]].append(row["episode_index"])
    families: dict[str, Any] = {}
    single_families = 0
    multi_families = 0
    for family in sorted(by_family):
        indices = by_family[family]
        observed = sorted({len(annotations[str(index)]["action_steps"]) for index in indices})
        entry: dict[str, Any] = {
            "episodes": len(indices),
            "split_episodes": {"train": len(indices), "val": 0, "test": 0},
        }
        if len(observed) == 1:
            entry["expected_subtask_count"] = observed[0]
        else:
            entry["expected_subtask_counts"] = observed
            entry["variable_subtask_count"] = True
        if observed == [1]:
            single_families += 1
        else:
            multi_families += 1
        families[family] = entry
    variable = sorted(
        family for family, entry in families.items() if entry.get("variable_subtask_count")
    )
    total_subtasks = sum(len(value["action_steps"]) for value in annotations.values())
    semantic_stage_units = sum(
        len(
            {
                int(step.get("info", {}).get("semantic_stage_index", stage_index))
                for episode_index in by_family[family]
                for stage_index, step in enumerate(
                    annotations[str(episode_index)]["action_steps"]
                )
            }
        )
        for family in by_family
    )
    if semantic_stage_units != 77:
        raise ValueError(
            f"expected 77 semantic family-stage units, got {semantic_stage_units}"
        )
    return {
        "schema_version": SPLIT_SCHEMA_VERSION,
        "recipe": "official50-clean50-stage-success-v6-22s28e-train2500-v2",
        "assignment": {
            "algorithm": "authoritative official task order; all 2500 episodes assigned to train",
            "salt": "none",
            "ratios": {"train": 1.0, "val": 0.0, "test": 0.0},
            "split_order": ["train", "val", "test"],
            "assignment_sha256": assignment_hash,
            "assignment_sha256_encoding": "canonical compact sorted-key JSON of episodes rows",
        },
        "source": {**hashes, "dataset_metadata_sha256": metadata_digest(hashes)},
        "contracts": {
            "episode_atomic": True,
            "family_stratified": True,
            "free_form_language_family_inference": False,
            "normalization_stats_source_split": "train",
            "normalization_stats_must_not_use": ["val", "test", "excluded"],
            "goal_graph_version": None,
            "materialized_annotation_goal_graph_version": GOAL_GRAPH_VERSION,
            "stage_success_contract_version": STAGE_CONTRACT_VERSION,
            "stage_boundary_source": (
                "same-seed recorded-trajectory replay; first true frame"
            ),
            "online_switch_confirmation_steps": 1,
            "online_switch_latch": "monotonic",
            "online_switch_catch_up": "furthest_satisfied_stage",
            "visual_goal_policy": "one fixed expert frame per episode-stage; no goal bank",
            "canonical_task_text_conditioning": True,
            "subtask_text_conditioning": False,
            "sampling_balance": "family_stage",
            "windows_per_family_stage": 6400,
            "tail_padding": True,
            "handoff_prefix_frames": 32,
            "handoff_prefix_fraction": 0.25,
            "semantic_family_stage_units": semantic_stage_units,
            "allowed_variable_subtask_families": variable,
            "strict_official50_clean50": True,
        },
        "excluded_families": [],
        "summary": {
            "input_episodes": 2500,
            "input_families": 50,
            "retained_episodes": 2500,
            "retained_families": 50,
            "single_subtask_families": single_families,
            "multi_subtask_families": multi_families,
            "semantic_family_stage_units": semantic_stage_units,
            "chunk_length": 32,
            "by_split": {
                "train": {
                    "episodes": 2500,
                    "subtasks": total_subtasks,
                    "strict_windows": None,
                    "short_subtasks": None,
                },
                "val": {"episodes": 0, "subtasks": 0, "strict_windows": 0, "short_subtasks": 0},
                "test": {"episodes": 0, "subtasks": 0, "strict_windows": 0, "short_subtasks": 0},
                "excluded": {"episodes": 0, "subtasks": 0, "strict_windows": 0, "short_subtasks": 0},
            },
        },
        "families": families,
        "episodes": rows,
    }


def create_symlink(link: Path, target: Path) -> None:
    if not target.exists():
        raise FileNotFoundError(target)
    link.symlink_to(target, target_is_directory=target.is_dir())


def build_runtime(
    base_root: Path,
    raw_root: Path,
    output_root: Path,
    annotations: dict[str, dict[str, Any]],
    mapping_rows: list[dict[str, Any]],
    family_map: dict[str, Any],
    goal_graph: dict[str, Any],
    audit: dict[str, Any],
    stage_boundary_rows: list[dict[str, Any]],
    stage_boundaries_sha256: str,
) -> None:
    if output_root.exists() or output_root.is_symlink():
        raise FileExistsError(
            f"refusing to overwrite existing output root: {output_root}"
        )
    output_root.parent.mkdir(parents=True, exist_ok=True)
    staging = output_root.with_name(f".{output_root.name}.tmp.{os.getpid()}")
    if staging.exists():
        raise FileExistsError(staging)
    staging.mkdir()
    try:
        meta = staging / "meta"
        meta.mkdir()
        create_symlink(staging / "data", base_root / "data")
        create_symlink(staging / "videos", base_root / "videos")
        for name in ("info.json", "stats.json", "tasks.parquet", "episodes"):
            create_symlink(meta / name, base_root / "meta" / name)

        episode_rows = [
            {
                "episode_index": row["episode_index"],
                "tasks": [row["task"]],
                "length": row["length"],
            }
            for row in mapping_rows
        ]
        task_table = pq.read_table(base_root / "meta/tasks.parquet")
        task_rows = [
            {"task_index": int(row["task_index"]), "task": str(row["task"])}
            for row in task_table.to_pylist()
        ]
        write_jsonl(meta / "episodes.jsonl", episode_rows)
        write_jsonl(meta / "tasks.jsonl", task_rows)
        write_json(meta / "annotations.json", annotations)
        write_json(staging / "family_mapping_v1.json", family_map)
        write_json(
            staging / "manual_goal_graph_22s28e_stagev6_v2.json", goal_graph
        )
        write_json(staging / "boundary_audit_stagev6_v2.json", audit)
        write_jsonl(staging / "stage_boundaries_v6.jsonl", stage_boundary_rows)

        hashes = source_hashes(meta)
        manifest = build_manifest(annotations, mapping_rows, hashes)
        manifest_path = staging / "train2500_manifest_stagev6_v2.json"
        write_json(manifest_path, manifest)

        source_stats_path = base_root / "meta/stats.json"
        source_stats = json.loads(source_stats_path.read_text(encoding="utf-8"))
        source_action_stats = source_stats.get("action")
        if not isinstance(source_action_stats, dict):
            raise ValueError(f"source stats has no action block: {source_stats_path}")
        action_stats: dict[str, Any] = {}
        for key in ("mean", "std", "min", "max"):
            values = source_action_stats.get(key)
            if not isinstance(values, list) or len(values) != 14:
                raise ValueError(
                    f"source action stats {key!r} must contain 14 values"
                )
            action_stats[key] = values
        counts = source_action_stats.get("count") or []
        action_stats["provenance"] = {
            "dataset": str(output_root),
            "source_dataset": str(base_root.resolve()),
            "split": "train",
            "episode_count": 2500,
            "row_count": int(counts[0]) if counts else None,
            "source_stats_sha256": sha256_file(source_stats_path),
            "annotations_sha256": hashes["annotations.json"],
            "episode_manifest_sha256": sha256_file(manifest_path),
            "split_assignment_sha256": manifest["assignment"][
                "assignment_sha256"
            ],
            "padding_rows_included": False,
            "overlapping_windows_counted": False,
        }
        write_json(
            staging / "train2500_action_stats_stagev6_v2.json",
            action_stats,
        )

        artifact_names = [
            "meta/annotations.json",
            "meta/episodes.jsonl",
            "meta/tasks.jsonl",
            "family_mapping_v1.json",
            "manual_goal_graph_22s28e_stagev6_v2.json",
            "boundary_audit_stagev6_v2.json",
            "train2500_manifest_stagev6_v2.json",
            "train2500_action_stats_stagev6_v2.json",
            "stage_boundaries_v6.jsonl",
        ]
        runtime_meta = {
            "schema_version": SCHEMA_VERSION,
            "source_dataset_root": str(base_root.resolve()),
            "raw_annotation_source_root": str(raw_root.resolve()),
            "runtime_root": str(output_root),
            "layout": "lightweight symlink runtime; official data and videos are not copied",
            "total_tasks": 50,
            "episodes_per_task": 50,
            "total_episodes": 2500,
            "subgoal_tasks": sorted(SUBGOAL_TASKS),
            "episode_goal_tasks": sorted(
                {row["family"] for row in mapping_rows} - SUBGOAL_TASKS
            ),
            "goal_graph_version": GOAL_GRAPH_VERSION,
            "stage_contract_version": STAGE_CONTRACT_VERSION,
            "source_stage_boundaries_sha256": stage_boundaries_sha256,
            "training_goal_graph_version": None,
            "training_split": "train",
            "artifacts": {
                name: {"sha256": sha256_file(staging / name), "bytes": (staging / name).stat().st_size}
                for name in artifact_names
            },
            "symlinks": {
                "data": str(base_root / "data"),
                "videos": str(base_root / "videos"),
                "meta/info.json": str(base_root / "meta/info.json"),
                "meta/stats.json": str(base_root / "meta/stats.json"),
                "meta/tasks.parquet": str(base_root / "meta/tasks.parquet"),
                "meta/episodes": str(base_root / "meta/episodes"),
            },
        }
        write_json(staging / "runtime.meta.json", runtime_meta)
        (staging / "BUILD_COMPLETE").write_text(
            sha256_file(staging / "runtime.meta.json") + "\n", encoding="utf-8"
        )
        staging.rename(output_root)
    except Exception:
        shutil.rmtree(staging, ignore_errors=True)
        raise


def print_audit(audit: dict[str, Any], goal_graph: dict[str, Any]) -> None:
    print(json.dumps(audit["summary"], indent=2, sort_keys=True))
    print("family\tmode\tcounts\tstrategies")
    for family, row in goal_graph["families"].items():
        print(
            f"{family}\t{row['mode']}\t{row['count_histogram']}\t"
            f"{row['boundary_strategy_histogram']}"
        )


def main() -> int:
    args = parse_args()
    annotations, mapping_rows, family_map, extras = build_records(
        args.base_root, args.raw_root, args.stage_boundaries
    )
    goal_graph = extras["goal_graph"]
    audit = extras["audit"]
    print_audit(audit, goal_graph)
    if args.audit_only:
        return 0
    build_runtime(
        args.base_root,
        args.raw_root,
        args.output_root,
        annotations,
        mapping_rows,
        family_map,
        goal_graph,
        audit,
        extras["stage_boundary_rows"],
        extras["stage_boundaries_sha256"],
    )
    print(f"BUILD_OK={args.output_root}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
